### PR TITLE
Converts stabby lambda to old-fashioned lambda

### PR DESCRIPTION
**Pull request by jphenow**
Slightly more compatible with older syntaxes

### CODE REVIEW

**Comment by jphenow** [comment]
@jeremy when you get a second, could you take a gander? I have some code that forces it within our project but this seems like a better approach if we can do it.

**Comment by jeremy** [comment]
Thanks for upstreaming!

**Comment by jphenow** [comment]
Thanks @jeremy!

**Comment by fotos** [comment]
@jeremy :wave: can we get a new tag (`3.2.7`) with this commit?

It may be insignificant but since `trashed` [mentions it supports Ruby 1.8](https://github.com/basecamp/trashed#keep-an-eye-on-resource-usage) and since this is [not the case since "3.0.0"](https://github.com/basecamp/trashed/commit/551e2341a5aae14f40544bc0a314ba041e932b20#diff-986bb9f5e0b7c3c7823c8f37e0672a86R14) (it's not tagged in the repo but I checked the code in the gem) maybe it's worth releasing a gem that supports Ruby 1.8?

I want to avoid forking the project for 2 lines. 👼

**Comment by jeremy** [comment]
@fotos [tagged](https://github.com/basecamp/trashed/releases/tag/v3.2.7) and [released](https://rubygems.org/gems/trashed/versions/3.2.7)!

**Pull request closed without merging**
